### ISSUE TITLE
Admonitions

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-redesign-prototype#12]
Some admonitions use titles.  Can this be supported in the doc template?  

http://docutils.sourceforge.net/docs/ref/rst/directives.html#specific-admonitions

![admonition_with_title](https://cloud.githubusercontent.com/assets/6391769/9259096/91e4b9ec-41c4-11e5-9de3-e7ceba81144e.png)

Although this example might not be the best; there are some cases where the content of an annotation could be clarified with the addition of a title.

**Comment by ktbartholomew** [comment]
The problem with showing titles the way Sphinx produces them is that it will show them _whether you specify a title or not_. For example, this RST:

```ReST
.. note::

Nobody puts baby in a corner
```

Will output this HTML:

```html
<div class="admonition note">
    <p class="first admonition-title">Note</p>
    <p class="last">Nobody puts baby in a corner.</p>
</div>
```

This generic admonition title adds visual clutter that distracts from the truly important content, which is everything that follows. Unfortunately, there's no way for us to distinguish an admonition with a default title from one with a specifically-provided title.
 
We're very intentionally trying to limit clutter inside of admonitions, and a large part of this strategy is to replace admonition titles with easy-to-differentiate and less-distracting colors and icons. @technabors may be able to weigh in on this design decision, as well.

**Comment by meker12** [comment]
Ideally, an admonition would be short and sweet, but sometimes they are more complex with titles, bulleted lists, code samples, and so on.  

I understand the point about removing visual clutter, and the title is probably not the most critical thing.  

But now I wonder-- does the design support admonitions that have multiple paragraphs, itemized lists, and so on.  Typically, an admonition won't have too much of that, but sometimes the information in an admonition might need it.  Does the template handle such cases.  Images doesn't have any notes like that.  Here's an [example from DNS](http://docs.rackspace.com/cdns/api/v1.0/cdns-devguide/content/POST_createDomain_v1.0__account__domains_domains.html):

![4_2_3_ create_domain - cloud_dns_developer_guide_ - api_v1_0](https://cloud.githubusercontent.com/assets/6391769/9264086/31433be4-41e8-11e5-9d73-180bc3ea62d2.png)

Here's the concern:  We are trying to complete the migration with the current content without having to do too much editing in the process.  After the migration completes, we will be working with the RST content to improve the organization and structure of the content as a separate and more comprehensive initiative.

So, the UX might need to support some less than perfect content in the short term in order to get all the content migrated to the new platform in a timely manner.  

Also, *some* of the funky formatting in the current documentation is because of limitations in the DocBook templates and transformations -- I'm hoping that the new UX templates will provide more flexibility for adding and adapting styles based on content requirements.  We'll need a process for those sorts of requests at some point.
